dist: trusty
sudo: required
env:
  - export DISPLAY=:99.0
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
before_install:
  # stuff needed for qt5 which is for GUI  
  - sudo apt-add-repository -y ppa:beineri/opt-qt551-trusty
  # test/start GUI
  - sh -e /etc/init.d/xvfb start
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools
before_script:
  # Run your build commands next
  - mkdir build
  - cd build/
  - cmake ../ 
script:
  - make
  # test example 1 

