dist: bionic

sudo: required

env:
  - DOCKER_REPO = nsfcareer/femtech

language:
  - cpp

services:
  - docker

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - libblas-dev 
      - liblapack-dev
      - openmpi-bin 
      - openmpi-common 
      - libopenmpi-dev
      - python-numpy

before_install:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - python --version

before_script:
  # Run your build commands next
  - mkdir build
  - cd build/
  - cmake .. -DEXAMPLES=ON -DEXAMPLE9=ON -DEXAMPLE1=ON -DEXAMPLE10=ON -DEXAMPLE5=ON
  - if [ "$TRAVIS_BRANCH" = "CI" ]; then 
      docker pull nsfcareer/femtech:production || true; 
    fi

script:
  - pwd
  - make -j 4 
  # test example 9
  - cd ./examples/ex9/
  - mpirun -n 1 --mca btl_base_warn_component_unused 0 ex9 1-elt-cube.k
  - python compareResults.py
  # test example 1
  - cd ../ex1
  - mpirun -n 2 --mca btl_base_warn_component_unused 0 ex1 mixed-hex-tet.k
  # test example 10
  - cd ../ex10
  - mpirun -n 1 --mca btl_base_warn_component_unused 0 ex10 1-elt-tet.k
    # Build docker image if on develop branch
  - if [ "$TRAVIS_BRANCH" = "CI" ]; then 
      cd ../../;
      mkdir builddocker;
      docker build --pull --cache-from nsfcareer/femtech:production --tag nsfcareer/femtech:production -f Dockerfile builddocker; 
    fi

after_script:
  - if [ "$TRAVIS_BRANCH" = "CI" ]; then docker images; fi

before_deploy:
  - if [ "$TRAVIS_BRANCH" = "CI" ]; then docker login -u "$CONTAINER_USER" -p "$CONTAINER_PASS"; fi

deploy:
  provider: script
  script: docker push nsfcareer/femtech:production
  on:
    branch: CI
