

set termoption dashed
set style line 1 lc rgb "#FF0055" lt 1
set style line 2
set style line 3
set style line 4

set xlabel "Time (s)"
set ylabel "Displacement (m)"

set key left top
set terminal png size 1024,768
set output "plot.png"
plot "plot.dat" using 1:2  ls 1 title "DispX",  \
		 "plot.dat" using 1:3  ls 2 title "DispY",  \
		 "plot.dat" using 1:4  ls 3 title "DispZ",  \
     "abaqusNoDamping.csv" using 1:2  ls 4 title "ABAQUS DispZ"  
